apiVersion: v1
kind: Service
metadata:
  labels:
    app: jira
  name: jira-cloud
spec:
  ports:
  - name: https
    nodePort: 31724
    port: 443
    protocol: TCP
    targetPort: 443
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: prometheus
    port: 2990
    protocol: TCP
    targetPort: 2990
  selector:
    app: jira
  type: LoadBalancer
