---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  name: storage-gce
parameters:
  type: pd-standard
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jira-storage-claim
spec:
  storageClassName: "storage-gce"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
